Commands to make the bra ket
$$\newcommand{\ket}[1]{\left|{#1}\right\rangle}$$
$$\newcommand{\bra}[1]{\left\langle{#1}\right|}$$

McWeeny method to describe Slater orbitals with Gaussian orbitals:  
Normal $STO$ - Slater Type Orbital  
$\Psi_s = R_{n_s} Y_{lm}$, $R_n (r) = ((2n_s)!)^{-1/2} (\frac{2Z}{n_s})^{n_s +1/2 rn_s -1} e^{-\frac{Z}{n_s}r}$

Gaussian type orbitals
$$R_{ng} (r) = N_i Z^{-(n_g -1)} \rho^{n_g -1} e^{-\alpha_i \rho^2}$$
$$N_i = \Bigg[\frac{2^{2n_g + 1/2}}{(2n_g-1)!!\sqrt{n}}\Bigg]^{1/2} (Z^2 \alpha_i)^{(2n_g +1)/4}$$


By taking the average of $Z^{-2}H_s$ over the orbitals, you can obtain the equations needed to first derive the variational principle

In [2]:
import math
import numpy as np
def gto_xg_xg(ai, aj, ng):
    return (2.0*(ai*aj)**(1/2)/(ai+aj))**(ng+0.5)
def gto_xg_ZH_xg(ai,aj,ns,ng):
    return ((2*ng+1)*(ai*aj/(ai+aj)) + (ns*(ns-1) - ng*(ng-1))/(2*ng-1)*(ai+aj) -  math.factorial(ng -1)*(math.sqrt(2)*(2**ng)/(math.factorial(math.factorial(2*ng -1))*math.sqrt(math.pi)) * (ai+aj)**(1/2)))*gto_xg_xg(ai,aj,ng)
def fn1(ng):
    return 2*ng+1
def fn2(ns,ng):
    return (ns*(ns-1) - ng*(ng-1))/(2*ng-1)
def fn3(ng):
    return math.factorial(ng-1)/(math.factorial(math.factorial(2*ng-1)) *math.sqrt(math.pi))
print(str(fn1(1))+ "fn2 " +str(fn2(1,1))+"fn3"+str(fn3(1)))


3fn2 0.0fn30.5641895835477563


$\bra{X_{g,i}} Z^{-2} H_s\ket{X_{g,i}} = f1 *\frac{a_i a_j}{a_i +a_j} + f2 * (a_i+a_j) - f3 * (a_i+a_j)^{\frac{1}{2}} \bra{X_{g,i}} \ket{X_{g,j}}$  
$f1 = 2n_g -1$  
$f2 = \frac{n_s(n_s-1) - n_g (n_g-1)}{2n_g -1}$  
$f3 = \frac{(ng-1)! 2^n}{(2n_g-1)!!\sqrt{\pi}}$  
$\bra{X_{g,i}} \ket{X_{g,j}} = \frac{2(a_ia_j)^{1/2}}{a_i+a_j}^{n_g+\frac{1}{2}}$   


$\frac{d}{da} = f1 * 2a + 2f2 - f3 *(2ai)^{-\frac{1}{2}}$
for ns = ng, f2 = 0, therefore the min a is 1/2 (f3/f2)^2/3


$\bra{X_{g,i}} \ket{X_{g,j}}$  
$\bra{X_{g,i}} Z^{-2} H_s\ket{X_{g,j}}$

In [25]:
import scipy.special as sp
from numpy import pi

def dfact(x):
    n = (x + 1.)/2.
    return 2.**n * sp.gamma(n + 0.5)/(pi**(0.5))

def d_xg_ZH_xg(a,ns,ng):
    """Assuming i=j"""
    return (2*ng+1)*a + 2 * (ns*(ns-1) - ng*(ng-1))/(2*ng-1)

def ideal_a(ng,ns):
    return (math.factorial(ng-1)*(2**(ng))*math.sqrt(2)/(dfact(2*ng-3) *math.sqrt(math.pi) *(4*ng+4*ns*(ns-1)-1)))**2
def ideal_ZH(ng,ns):
    return -1/2 * (2*ng-1)/(4*ng+4*ns*(ns-1) -1) *((math.factorial(ng-1)*(2**ng)*math.sqrt(2)/(dfact(2*ng-1) *math.sqrt(math.pi)))**2)

ng = np.arange(1,7)
ns = np.arange(1,6)
a_opt = np.zeros((len(ng),len(ns)))
ZH_opt = np.zeros((len(ng),len(ns)))
for i in ng:
    for j in ns[(i)//2:]:
        a_opt[i-1][j-1] = ideal_a(i,j)
        ZH_opt[i-1][j-1] = ideal_ZH(i,j)
print(np.transpose(a_opt))
print(np.transpose(ZH_opt))

[[0.28294212 0.         0.         0.         0.         0.        ]
 [0.02104528 0.04527074 0.05016148 0.         0.         0.        ]
 [0.00349311 0.01059929 0.01478228 0.01714395 0.01841989 0.        ]
 [0.00097904 0.00336725 0.00520204 0.0065699  0.00758707 0.00834108]
 [0.00036964 0.00134574 0.00218673 0.0028893  0.00347499 0.00396337]]
[[-0.42441318  0.          0.          0.          0.          0.        ]
 [-0.11574905 -0.11317685 -0.09530682  0.          0.          0.        ]
 [-0.04715702 -0.05476299 -0.05173799 -0.04775814 -0.04400307  0.        ]
 [-0.02496548 -0.03086641 -0.03069203 -0.02956456 -0.02824078 -0.02691894]
 [-0.01534024 -0.01951325 -0.01989923 -0.01960597 -0.01911245 -0.01855577]]


In [15]:
n_g =1
n_s =1
import scipy.special as sp
from numpy import pi
import math

def dfact(x):
    n = (x + 1.)/2.
    return 2.**n * sp.gamma(n + 0.5)/(pi**(0.5))

def fn1(ng):
    return 2*ng+1
def fn2(ns,ng):
    return (ns*(ns-1) - ng*(ng-1))/(2*ng-1)
def fn3(ng):
    return math.factorial(ng-1)/(dfact(2*ng-1) *math.sqrt(math.pi))
a = [0.2,0.5,2,15]
a2 = a
def partial_x_ng_1(x,y,k,l,m):
    return (y*(l*(x - 3*y)*((x + y)**2) + math.sqrt(x + y)*(j*((x + y)**2) *(x + 3*y) + k*x*y*(-3*x + 7*y))))/(math.sqrt(2)*math.sqrt(math.sqrt(x*y)/(x + y))*((x + y)**(9/2)) )
k = [0.0]*4
for i in range(4):
    for j in range(4):
        k[i] += partial_x_ng_1(a[i],a[j],fn1(n_g),fn2(n_s,n_g),fn3(n_g))
for i in range(4):
    a[i] = a[i]- 0.001*k[i]
        
k = [0.0]*4
#for i in range(4):
#    for j in range(4):
#        k[i] += partial_x_ng_1(a[i],a[j],fn1(n_g),fn2(n_s,n_g),fn3(n_g))
#for i in range(4):
#    a[i] = a[i]- 0.1*k[i]

print(k)
print(a)
    


[0.0, 0.0, 0.0, 0.0]
[0.1679566064215235, 0.4761239886065956, 1.9859962135391438, 14.995930062727078]


In [10]:
(y (l (x - 3 y) (x + y)^2 + Sqrt[x + y] (j (x + y)^2 (x + 3 y) + k x y (-3 x + 7 y))))/(Sqrt[2] Sqrt[Sqrt[x y]/(x + y)] (x + y)^(9/2))

SyntaxError: invalid syntax (3662348872.py, line 1)